### PR TITLE
allowing to overwrite feedback lsn calculation

### PR DESCRIPTION
**Pull request by miki725**
this is useful when lsn is manually tracked somehow and therefore we only want to notify PG of last successful LSN which was processed, which is not necessarily consumed

implementation is done in backwards compatible way, just allows to pass `getFeedbackLsn` option

### CODE REVIEW

**Comment by wwindcloud** [comment]
Thanks for your PR. But haven't you consider not executing the callback function downstream instead? I believe the confirmed LSN is only effective after the last COMMIT message, so so long you don't invoke the callback() function at your COMMIT message, the whole transaction will be going to replay if you subscribe again if you stopped the stream or crashed. Once you consume the your transaction, you can invoke callback() and proceed as usual.

Personally I don't see a point in this feedback function unless you want to allow replay across transactions.

**Comment by miki725** [comment]
We do some processing on all subscribed wal events which sometimes takes a little time. Feedback function runs on an interval. As such it can notify PG that some LSN has successfully been consumed but we didnt process it yet. We have a requirement that we must process all wal events. Therefore we would like to only send confirmation lsn when we successfully finished processing that wal event. If for some reason we finish processing but fail to send updated confirmation lsn, its ok for us to reprocess/replay the same event. Currently that is not possible as far as I know but I could be missing something. You mentioned a callback function however not sure how that impacts what lsn number feedback function sends to PG.

Visually this pr changes:

currently:

```
transaction1 
transaction2 <- being processed
transaction3
transaction4 <- feedback sends this as it was successfully consumed from WAL
```

pr allows to achieve this:

```
transaction1 <- we nudge feedback to send this as it was last successfully processed
transaction2 <- being processed
transaction3
transaction4 <- consumed from WAL into processing buffer
```

Note that by default, current behavior is preserved. The PR only adds an option which can optionally allow to implement requirements like we have above.

**Comment by wwindcloud** [comment]
Let's throw some code here to aid discussion
```javascript
class ConsumeStream extends OutputStream {
   write(data, encoding, callback) {
      // Assume you receive the logical replication message from upstream
      consumeData(data).then(() => {
         // You have consumed the data, you want to move on, so you execute cb
         callback()
      })
   }
}
```
Assuming your *consumeData* returns a promise, You can do very lengthy processing all you want, if things go south, the transaction will be replayed again. Until you are done, you can just call **callback()** and proceed, the confirmed LSN is handled automatically for you. The purpose of my library is to help you to do all the bookkeeping so you can focus entirely on the data itself, having you to handle the LSN seems to be a little backward defeating the purpose of this library.

So in essence from your example
```
transaction1 <- on commit message, finish your processing, execute callback()
transaction2 <- on commit message, finish your processing, execute callback()
transaction3 <- on commit message, finish your processing, execute callback()
transaction4 <- on commit message, finish your processing, execute callback()
```

Am I reading it right? Unless you want to process multiple transactions in one go, I don't see a need to confirm LSN manually.

**Comment by miki725** [comment]
Thanks for the response. I see what you mean about the callback. We are using the stream in a loop so didnt see how that connected:

```
for await (const chunk of stream.pipe(this.pgParser) {}
```

And yes you are right we are consuming multiple transactions at the same time. Actually we use cluster API to spread the load to multiple cores. We needed that for higher throughput. Since all child processes can be processing transactions at different rates, we are tracking in the main process what transactions finished being processed. This allows us to compute which last lsn should be sent to pg. Something like:

```
transaction1 <- finished processing by child 1
transaction2 <- finished processing by child 2; we want to send this lsn
transaction3 <- being processed in child 3
transaction4 <- consumed from WAL and sent to child 1 for processing
transaction5 <- consumed from WAL and sent to child 2 for processing
```

I understand the library is meant to hide the bookkeeping from the consumer however not sure there is simpler way to achieve this without tracking lsn somewhere on the higher level. Thoughts?

**Comment by wwindcloud** [comment]
Well, I see now. I think supporting your use case is justified. My library should provide a way for the consumer to confirm LSN at their pace.

However I don't think inserting a *getFeedbackLsn* is a good approach. Instead, I think I should add a function *flush(lsn)* into PgSubscriptionStream, that way you can call the function directly once your LSN is consumed properly. Here's a rough example I envision how it works

```javascript
const stream = new PgSubscriptionStream({
    ... // Your settings
    autoFlush: false  // A new option to disable auto LSN flushing, default is true 
                      // which is the same behavior as current version
})

for await (const chunk of stream.pipe(this.pgParser) {
    const shouldFlush = consume(chunk)

    // I don't think this is how your system works, but just to give you an idea, 
   // once you confirm your LSN is saved, you can call stream.flush anywhere with the LSN of the latest confirmed chunk 
   // and the library should take care of the rest
    if (shouldFlush) {
        const {lsn} = chunk
        stream.flush(lsn)
    }
}
```

Does it sound ok to you using this approach?

**Comment by miki725** [comment]
Thanks. I think that would work. How would that account for the interval though?

https://github.com/wwindcloud/pg-subscription-stream/blob/157a2ae7b33d494cb01cb1c988a77095e3ea4dc8/pg-subscription-stream.js#L26-L28

Would the interval be disabled for manual flush?

I guess Im not sure what is the intent of the interval given that the confirmation is also sent when consuming a chunk:

https://github.com/wwindcloud/pg-subscription-stream/blob/157a2ae7b33d494cb01cb1c988a77095e3ea4dc8/pg-subscription-stream.js#L65

If manually calling `flush` would account for both calls, this sounds great!

**Comment by wwindcloud** [comment]
> Thanks. I think that would work. How would that account for the interval though?
> 
> https://github.com/wwindcloud/pg-subscription-stream/blob/157a2ae7b33d494cb01cb1c988a77095e3ea4dc8/pg-subscription-stream.js#L26-L28
> 
> Would the interval be disabled for manual flush?

If you check [wal_sender_timeout](https://www.postgresql.org/docs/current/runtime-config-replication.html#GUC-WAL-SENDER-TIMEOUT), the server will terminate the connection if there's no feedback, so that's why there's an interval, it's used for setting how frequently the keepalive message be sending back to the server such that the subscription can continue to receive WAL messages. it's just that the *confirm_flush_lsn* is sent alongside with the keepalive message as well. To support your use case, I will modify to only send the last confirm_flush_lsn every feedback until an acknowledgement of the the next LSN is received from the consumer.
So no need to worry about that interval.

**Comment by miki725** [comment]
great! that makes sense. thank you for quick feedback.

should I work on your proposal? I can update this pr if you like

**Comment by wwindcloud** [comment]
I have committed the change, please check to see if it works for you and I will make a version bump afterwards.

The function is *confirmLSN*, and the option *autoConfirmLSN*, since from the point of view of the consumer, this library is not flushing LSN but rather to confirm the LSN being flushed, so the name change, other than that, things should work pretty much what we have discussed. Thanks.

**Comment by miki725** [comment]
it works! thank you. there is one edge case now where initially it sends lsn of 0 before any transactions are confirmed. sending pr for that

**Pull request closed without merging**
